# jenkins/vars.yml
---
# Official Jenkins image
jenkins_image_official: "jenkins/jenkins:lts-jdk21"

# Docker container and volume Information
jenkins_container_name: "bhevs-jenkins"
jenkins_volume_name: "jenkins_data"
jenkins_network_name: "jenkins-net"
jenkins_host_port_http: "80"
jenkins_host_port_agent: "50000"