# nginx/vars.yml
# Domain
jenkins_domain: "jenkins.bhevs.co.kr"

# Jenkins SSL Certificate Variables
jenkins_container_name: "bhevs-jenkins"
jenkins_network_name: "jenkins-net"
jenkins_volume_name: "jenkins_data"

# Nginx Variables
nginx_container_name: "bhevs-nginx-proxy"
certs_remote_dir: "/etc/ssl/jenkins"
jenkins_host_port_http: 80
jenkins_host_port_https: 443
nginx_conf_path: "/etc/jenkins/nginx.conf"

nginx_image: "nginx:latest"
jenkins_image: "jenkins/jenkins:lts-jdk21"
timezone: "Asia/Seoul"
file_mode_dir: "0755"
file_mode_file: "0600"
pfx_local_path: ""
pfx_password: ""
