# debug.yml
---
- hosts: localhost
  connection: local
  vars_files:
    - nginx/secrets_test.yml

  tasks:
    - name: ðŸ¤« Display vaulted secrets for verification
      ansible.builtin.debug:
        msg:
          - "PFX File Path: {{ pfx_local_path }}"
          - "PFX Password: {{ pfx_password }}"