# nexus/vars.yml
---
# Sonatype Nexus 3 image
nexus_image: "sonatype/nexus3:latest"

# Docker container and volume Information
nexus_container_name: "bhevs-nexus"
nexus_volume_name: "nexus_data"
nexus_network_name: "nexus-net"
nexus_host_port_http: "32510"