$ANSIBLE_VAULT;1.1;AES256
30303563636166306135616135613261323637316365353864613332643036303935323964653730
3163333332363738323866386238333632376138373935640a336130336464323531383163366165
63663936393562623139386531643733353835663163353964306239303436376264376561313930
3331353731363536320a656237326239663631366539373461366438616135633761356138316533
63313631393735333365313434646466343537393835303332336336623131373332323433343233
32363337323466333464343963343339323463336535306134343564386237326262653331396134
37643832623662356364376566383531653166393035323535666232356263623133303836333232
65643161656331663838383563656339386333376537346562306637663133316631643562313261
35323764373437396365613837366539623039306162326530636364653430666232373236663362
33393738653663636334313036643337613036373530366162333334363961363030396631326432
32313131326634343066353137393831636633343663303638306532313431616636346237356630
62306365383465666365
