# nginx/vars.yml
# 젠킨스 도메인
jenkins_domain: "jenkins.bhevs.co.kr"

# --- 아래는 기존 jenkins/vars.yml과 일치시켜야 하는 값 ---
jenkins_container_name: "bhevs-jenkins"
jenkins_network_name: "jenkins-net"
jenkins_volume_name: "jenkins_data"

nginx_container_name: "bhevs-nginx-proxy"
certs_remote_dir: "/etc/ssl/jenkins"
jenkins_host_port_http: 80
jenkins_host_port_https: 443