# docker/vars.yml
## file
docker_gpg_key_dir: "/etc/apt/keyrings"
docker_gpg_key_path: "{{ docker_gpg_key_dir }}/docker.gpg"
docker_repo_path: "/etc/apt/sources.list.d/docker.list"
docker_repo_filename: "docker"
docker_gpg_key_mode: "0755"

## URL
docker_gpg_key_url: "https://download.docker.com/linux/ubuntu/gpg"
docker_repo_url_base: "https://download.docker.com/linux/ubuntu"

## packages
docker_prereq_packages:
  - ca-certificates
  - curl
  - gnupg

docker_packages:
  - docker-ce
  - docker-ce-cli
  - containerd.io
  - docker-buildx-plugin
  - docker-compose-plugin

## setting
ansible_user_id: "bhevs-admin"
docker_group_name: "docker"